### ISSUE TITLE
Option to change the date format

### ISSUE THREAD

**Issue by mfsoup** [HolodexNet/Holodex#218]
It would be nice to be able to change the displayed dates from M/D/Y to YYYY-MM-DD (with leading zeroes) or another date format. The option to display 24 hour clock would also be helpful.

**Comment by sphinxrave** [comment]
localization is one of the hardest parts of building a global website nobody thinks about (and sometimes our brains don't even think of it), thanks for the suggestion!

**Comment by terry182** [comment]
anyone working on it? I would like to give it a shot.

**Comment by sphinxrave** [comment]
I've given it two separate tries the problem is dayjs ... does not seem to have the right dating configuration setup for their localizations? it's very strange. Feel free to give it a shot terry!

**Comment by terry182** [comment]
> I've given it two separate tries the problem is dayjs ... does not seem to have the right dating configuration setup for their localizations? it's very strange. Feel free to give it a shot terry!

I have the formatting working for me here. But I would like to discuss on how should we implement this option.  I have 3 ideas in my mind rn, 

1.  Just a simple toggle that switches the date ISO 8601 format. (YYYY-MM-DD)
2.  List some commonly used date formats for users to choose (using example date or today)
     I am thinking of the list like this:
    1. yyyy-mm-dd
    2. yyyy-dd-mm
    3. mm/dd/yyyy
    4. dd/mm/yyyy

3. Let users write their own format string.

**Comment by RiceCakess** [comment]
Sorry for the late reply. I think we should go with option 2. Introduce a new setting for date format with 3 options: 

* Relative Date (3 months ago, 2 hours ago) format for everything, right now it only does relative if it's less than 24 hr. Im interested in seeing relative for all times

* Current setting, which is localized
* Alternate of current with yyy-mm-dd with 24 hour

**Comment by sphinxrave** [comment]
I slightly disagree, I think we should patch up the problems in dayjs localization configuration and introduce additional locales such as English (British) and English (Canadian) in addition to English (US).

The way I see it DayJS prints out the same format for `LLL` and `ll` and `LL` standard, for Canadian and British and US english (may be a bug in how we're using it?)

https://github.com/iamkun/dayjs/tree/dev/src/locale

Canadian:
```
    L: 'YYYY-MM-DD',
    LL: 'MMMM D, YYYY',
    LLL: 'MMMM D, YYYY h:mm A',
    LLLL: 'dddd, MMMM D, YYYY h:mm A'
```

British
```
    L: 'DD/MM/YYYY',
    LL: 'D MMMM YYYY',
    LLL: 'D MMMM YYYY HH:mm',
    LLLL: 'dddd, D MMMM YYYY HH:mm'
```


Overriding date format causes the current localization strategy to break apart, and dayjs is what's giving us nice "In 20 hours" kind of distance/absolute rendering (saving our localizers from that complexity). =/

**Comment by terry182** [comment]
I am thinking that we should not touch the relative time part, and modify those date displayed which have a distance larger 24 hours.  As the confusion we are addressing here only happens when the date is show in  `[0-12] [delimiter] [0-12] [delimeter] yyyy` format, only changing these kind of stuffs won't really cause too much of a complexity to localisers, imo.

**Comment by michaelnguyenm** [comment]
I agree with the ability to change locals for different localizations (en/en-ca/en-gb) as well as supporting different length formats, short and long when not redundant. These cover most of the variations that exist in most regions and are built into Day.js so it'll save the headache for both devs and translators.

> The way I see it DayJS prints out the same format for LLL and ll and LL standard, for Canadian and British and US english (may be a bug in how we're using it?)

It seems to work for me when I add as shown [here](https://day.js.org/docs/en/durations/locale#docsNav):
```
import "dayjs/locale/en-gb";
import "dayjs/locale/en-ca";
```
These imports are not needed for just "en" and other locales like "ja" and "id".

And then I change `lang` in `formatDistance` inside `src/utils/time.js` to "en-gb" or "en-ca" manually for:
```
if (Math.abs(dayjs().diff(time, "hour")) > 23)
        return `${localizedDayjs(time, lang).format("L")} (${localizedDayjs(time, lang).format("LT")})`;
```

Keep in mind that using "EN-GB" or "en-GB" does not work.

Some random sample times as rendered by Holodex for times > 23 hours for the lines of code above:

| Format | en                                     | en-ca                                  | en-uk                             | jp                                | id                                     |
|--------|----------------------------------------|----------------------------------------|-----------------------------------|-----------------------------------|----------------------------------------|
| l      | 7/2/2021 (3:00 PM)                     | 2021-7-2 (3:00 PM)                     | 2/7/2021 (15:00)                  | 2021/07/02 (15:00)                | 2/7/2021 (15.00)                       |
| ll     | Jul 2, 2021 (3:00 PM)                  | Jul 2, 2021 (3:00 PM)                  | 2 Jul 2021 (15:00)                | 2021年7月2日 (15:00)              | 2 Jul 2021 (15.00)                     |
| lll    | Jul 2, 2021 3:00 PM (3:00 PM)          | Jul 2, 2021 3:00 PM (3:00 PM)          | 2 Jul 2021 15:00 (15:00)          | 2021年7月2日 15:00 (15:00)        | 2 Jul 2021 pukul 15.00 (15.00)         |
| llll   | Fri, Jul 2, 2021 3:00 PM (3:00 PM)     | Fri, Jul 2, 2021 3:00 PM (3:00 PM)     | Fri, 2 Jul 2021 15:00 (15:00)     | 2021年7月2日(金) 15:00 (15:00)    | Jum, 2 Jul 2021 pukul 15.00 (15.00)    |
| L      | 07/02/2021 (3:00 PM)                   | 2021-07-02 (3:00 PM)                   | 02/07/2021 (15:00)                | 2021/07/02 (15:00)                | 02/07/2021 (15.00)                     |
| LL     | July 2, 2021 (3:00 PM)                 | July 2, 2021 (3:00 PM)                 | 2 July 2021 (15:00)               | 2021年7月2日 (15:00)              | 2 Juli 2021 (15.00)                    |
| LLL    | July 2, 2021 3:00 PM (3:00 PM)         | July 2, 2021 3:00 PM (3:00 PM)         | 2 July 2021 15:00 (15:00)         | 2021年7月2日 15:00 (15:00)        | 2 Juli 2021 pukul 15.00 (15.00)        |
| LLLL   | Friday, July 2, 2021 3:00 PM (3:00 PM) | Friday, July 2, 2021 3:00 PM (3:00 PM) | Friday, 2 July 2021 15:00 (15:00) | 2021年7月2日 金曜日 15:00 (15:00) | Jumat, 2 Juli 2021 pukul 15.00 (15.00) |

So the first observation is that supporting lll and LLL is a bit redundant as all it does is add the time. llll/LLLL adds the weekday which some may like but still is redundant on the time.

The second thing is that for "jp" in particular, there is no difference between l/L formats. So other locales might have cases like that as well.

One confusing bit is probably that Canada actually recognizes both the "UK" style and the "US" style of formatting date/time. Day.js does not use the government recommended 24-hour notation, but colloquially AM/PM is more popular?
https://en.wikipedia.org/wiki/Date_and_time_notation_in_Canada#Time
But for whatever reason that same 24-hour recommendation by the UK government is applied in en-gb and is used in Day.js even though AM/PM is more common colloquially?
https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom#Time

Not really sure how they decide when to use AM/PM and 24-hour (might also be good to get an opinion from someone from those regions), but it may be best to allow users to pick between AM/PM and 24-hour formats where applicable. However, as seen above, ja and id pretty much always do 24-hour in writing I think so allowing people to choose here isn't really useful.

**Comment by terry182** [comment]
> These imports are not needed for "en" by itself and other locales like "ja" and "id".
This is strange. From [the documentation](https://day.js.org/docs/en/i18n/changing-locale) they write that dayjs comes with en locale *only*. This means even "ja" and "id" should require such import, just like "de" in the example.

**Comment by michaelnguyenm** [comment]
Apologies I doubled-checked and the imports are done in `src\plugins\vuetify.js`

So the en-gb and en-ca can be imported there.

**Comment by sphinxrave** [comment]
yeah so is this like a viable option? I experimented with this and it just won't work properly - or at least, i'm not aware enough about timezone localization correctness to realize if what i'm coding is working in the correct direction.

**Comment by michaelnguyenm** [comment]
I should have more time this weekend to take a look at this. Unless @terry182 has been able to make any headway on it?

I think at the minimum we should support the long and short variants of dates and possibly the option of switching between 12 and 24 hour clock when applicable, but we would have to note which formats actually produce a change for each locale as seen in my comment above, https://github.com/HolodexNet/Holodex/issues/218#issuecomment-872356362 , particularly the jp case is one such example. This is so that we don't show any redundant options to the user in the settings. And maybe support ISO 8601 format dates (YYYY-MM-DD) as suggested by OP since that's not limited by locale.

**Comment by terry182** [comment]
@michaelnguyenm Sure. I only have the ISO-8601 and 12/24-hour format switch done (but it is a forced option using AM/PM.. dayjs didn't even think of using `午前/午後` in `jp` ), and didn't expect the solution to become that big. 

I can just try to implement the locale option this weekend too. It is always good to have another person working on the issue (as my code quality may not be that good). I will keep tracking the PRs so don't mind me if you want to work on this.

**Comment by RiceCakess** [comment]
I added and hooked up extra locales for British and Canadian dayjs formatting. You can give it a shot to see if it fulfills the gap, the only small quirk at the moment is that it won't take a effect without a page refresh

**Comment by RiceCakess** [comment]
Settings for British and Canadian was released a while ago, which should fix OP's issue. If more granular control is needed, feel free to reopen.
