### ISSUE TITLE
Feature request: Hide certain topics from video feed

### ISSUE THREAD

**Issue by ajhall** [HolodexNet/Holodex#271]
There are certain video types I'm rarely interested in (Apex or ARK, for example), but they're popular enough that my favorites feed is usually full of them. It would be nice if I could filter those out of my feed so I could see the stuff I'm interested in more easily.

The "topics" feature works great, so it would be perfect if we could use that in the other direction to hide videos that match a topic. Maybe it could be controlled with a new field in the "Video Feed Settings" section: select a list of topics, then exclude those from the favorites feed.

**Comment by ajhall** [comment]
I have this partially implemented, but I'm having trouble testing the favorites feed without logging in. I see this in Login.vue, but I can't figure out how to actually log in locally. Google login prints an error in the console, Discord login tells me "Invalid Oauth2 redirect_uri", and Twitter login sends me to the invalid address "localhost:2434/v2/user/login/twitter". Any advice?

I see this section in Login.vue, but I can't tell what to do with it. Any advice?
https://github.com/HolodexNet/Holodex/blob/e3d6f443046cc98ac7c2248d796d33b271d681a9/src/views/Login.vue#L103-L105

**Comment by michaelnguyenm** [comment]
Are you running the development server with `npm run serve` on the default port 8080? I only get those errors when I change ports. Well, Twitter is still broken but you should be able to test with Google/Discord at least.

**Comment by ajhall** [comment]
Ahh, I had something else on port 8080, so it was automatically using port 8082. I moved it to 8080 and it's working now. Thanks!
