### ISSUE TITLE
Holodex forgot to reuse old three dot menu HTML element under video stream thumbnail?

### ISSUE THREAD

**Issue by Trung0246** [HolodexNet/Holodex#306]
Version: 2.13

I'm pretty sure that the previous version (not sure which version, maybe 2.12 and older) didn't have this behavior, and instead reuse old HTML element as usual?
Seems like Holodex is forgot to reuse old menu HTML element and instead creating an entire new HTML element (by looking at the chrome console).

The bug in action:
https://streamable.com/7rchct

OS: Windows 10
Browser: Vivaldi 4.0.2312.33 (latest)

**Comment by RiceCakess** [comment]
:O Surprised you noticed. We reverted the change because we had to refactor some things for virtual scrolling for playlists, and we weren't really sure if there was any real performance implications for reusing the menu. Since the html element only gets created when it's clicked.

**Comment by Trung0246** [comment]
> :O Surprised you noticed. We reverted the change because we had to refactor some things for virtual scrolling for playlists, and we weren't really sure if there was any real performance implications for reusing the menu. Since the html element only gets created when it's clicked.

How did I found this bug? I was developing a personal Tampermonkey script to hook Holodex with streamlink instead of copy pasting the youtube link into command line everytime and somehow the script suddenly broke. That's how 😅

**Comment by sphinxrave** [comment]
Should just PR the functionality into Holodex as an experimental feature - we can have a section of settings "Labs" dedicated to odd but low-performance-impact features like that.

Gonna close the issue though since it's not something we intend on reverting
