### ISSUE TITLE
Holodex doens't show anything

### ISSUE THREAD

**Issue by hozikata** [HolodexNet/Holodex#307]
Like the title, it doesn't show anything exept the sidebar but its still not working even i click them. Its happened when i changed language to Vietnamese in another browser too.
![image](https://user-images.githubusercontent.com/87218760/125152267-b9d37b80-e175-11eb-9492-c0f1427a3e3d.png)

**Comment by RiceCakess** [comment]
Vietnamese is broken at the moment (along with the other new language), please wait until next update for the fix. Please use a different language for the time being

**Comment by hozikata** [comment]
i cant even goto the setting to do this

**Comment by RiceCakess** [comment]
Click the icon next to the setting

**Comment by hozikata** [comment]
alright, thank you
