### ISSUE TITLE
Multiview link wrongly generated/loaded for twitch

### ISSUE THREAD

**Issue by wipe2238** [HolodexNet/Holodex#315]
Setup
- Preset: Side Chat 2
- Upper frame: (manually added) https://www.twitch.tv/annacramling
- Lower frame: (top selector) Ollie

Generated link
https://holodex.net/multiview/AARMannacramlingannacramling%2CAMRMMi_lQetdd1IKureiji%2CRAHYchat1

When opening generated link, twitch stream is treated as youtube stream; upper frame leads to https://www.youtube.com/watch?v=annacramlin&feature=emb_imp_woyt now, which obviously doesn't work.

**Comment by RiceCakess** [comment]
Fixed in #318
