### ISSUE TITLE
EHOSTUNREACH in Node

### ISSUE THREAD

**Issue by Choooks22** [HolodexNet/Holodex#325]
Out of a sample of 20 requests to `/channels`, I only got 7 back.
This only occurs in node using either `axios` or `node-fetch`, fetching directly from browser, console, or `curl` doesn't have any issues.

**Comment by RiceCakess** [comment]
Hmm, could it be cloudflare? Although host unreachable either means the server is down or the network routing is bad. Assuming you already have the X-API-KEY set, maybe try running through a VPN

**Comment by Choooks22** [comment]
Ran the tests again with and without vpn, seems like it does work on node with a vpn.
But if it is a cloudflare issue, then why does it only break on node and not in browser fetch/curl? 🤔

**Comment by RiceCakess** [comment]
Not sure, do you have a location? Maybe check cloudflare status to see if the local servers there are working
