### ISSUE TITLE
Certain color schemes on mobile view might be too difficult to see

### ISSUE THREAD

**Issue by reymarkus** [HolodexNet/Holodex#334]
Certain color schemes when in mobile mode blend too much with their secondary color, which results in text being too difficult to read in the home tab switcher (live/upcoming, VODs, clips)

Okayu (purple/rose violet, dark mode)
![photo_2021-07-25_00-51-51-1](https://user-images.githubusercontent.com/46585888/126875583-7e73dc86-a32d-4256-a8a7-a5f774ac5ba8.jpg)

Pekora (orange/blue-silver, dark mode)
![photo_2021-07-25_00-51-51](https://user-images.githubusercontent.com/46585888/126875592-3e5ea21d-ee17-45c8-9b15-51eb9be6b1c4.jpg)

**Comment by sphinxrave** [comment]
thanks for the response, will try to figure something out...

**Comment by RiceCakess** [comment]
flipped the colors: 

![image](https://user-images.githubusercontent.com/3145205/126919317-7567a615-c36f-4fe6-879b-3c6482fd4375.png)

![image](https://user-images.githubusercontent.com/3145205/126919322-7537a014-6f3a-4d32-b326-3a98a6a79b4e.png)
