### ISSUE TITLE
request for translation prefix [KO] change

### ISSUE THREAD

**Issue by jsoon001** [HolodexNet/Holodex#349]
I'm not sure if korean filter can pick up [KR] prefix, but [KR] prefix is the most used prefix for translation. I hope TLdex can pick up [KR] as well.

**Comment by RiceCakess** [comment]
@alexkoala 

Ah, sorry I misconfigured the backend. It caught all the messages from yesterday, but was organized into "kr" instead of "ko"

It is fixed now. Can check this archive where it caught some translations: https://holodex.net/watch/nj1GHW0ytq4
