### ISSUE TITLE
Feature Request: displayed chat to be still same one when other panel stream is changed 

### ISSUE THREAD

**Issue by katoosky** [HolodexNet/Holodex#370]
Now:
> An chat index is not changed when other panel stream (index is smaller) is changed.
> And chat panel display same index stream with using new index
> So chat display other stream chat if remove/add other stream to panel (index is smaller than index displayed chat stream ) without remove/adding panel

I wanted:
> displayed chat to be still same one when other panel stream is changed

**Comment by sphinxrave** [comment]
I'm afraid the dev team didn't understand what this issue is about.

**Comment by RiceCakess** [comment]
Please feel free to leave a message in Japanese or your native language. We have translators on our team that can help with your issue/feature request.

**Comment by sphinxrave** [comment]
cleanup: closing issue due to lack of response. Feel free to respond at any time and we'll reopen 👍

**Comment by katoosky** [comment]
返信遅れてすみません。

現在はチャットパネルで表示している配信のパネルより先に追加したパネルの配信を空にすると、
チャットパネルで表示されているチャットが、一つあとに追加されたパネルの配信のチャットになります。

表示しているチャットのインデックスが一個ずれたままチャットパネルを再読込している？

これをパネルを空にしても、元々表示されていた配信のチャットを表示してほしいです。

Now：
Panel1 （StreamA）Panel2（StreamB）Panel3（empty）Panel（StreamC）ChatPanel（StreamB）
↓　Change Panel1 to be empty
Panel1 （empty）Panel2（StreamB）Panel3（empty）Panel（StreamC）ChatPanel（StreamC）

I want:
Panel1 （StreamA）Panel2（StreamB）Panel3（empty）Panel（StreamC）ChatPanel（StreamB）
↓　Change Panel1 to be empty
Panel1 （empty）Panel2（StreamB）Panel3（empty）Panel（StreamC）ChatPanel（StreamB）

![before](https://user-images.githubusercontent.com/38729985/129662315-08641d37-8b21-4b12-bfda-cf530b0afeec.png)
![after](https://user-images.githubusercontent.com/38729985/129662323-3b67fccb-ceff-4f53-b91c-852fdf471e65.png)
