### ISSUE TITLE
Feature Request: Display a number on Multiview tiles

### ISSUE THREAD

**Issue by johnchen40904** [HolodexNet/Holodex#379]
Sometimes, I found it frustrating when the selected videos didn't fill up the layout with the arrangement I expect. I wish there's a feature, which labels the tiles with numbers (1,2,3,4,5...), so that when you click multiple vtuber icons in an order, you'll be sure which video will appear in which tile.

**Comment by RiceCakess** [comment]
Not a very well known feature, but you can drag and drop to place the videos where you want it.

![ezgif-4-ada253e96532](https://user-images.githubusercontent.com/3145205/129675855-a7cee1d5-cec2-4bbe-8f18-1597804d00dc.gif)

**Comment by johnchen40904** [comment]
@RiceCakess 
Hmm…interesting! Never knew that XD
Though I still think the tile number thing might be a nice option to be included in the settings page someday 😅
