### ISSUE TITLE
TLs display the link of an emoji rather than the emoji

### ISSUE THREAD

**Issue by Machrischt** [HolodexNet/Holodex#382]
![image](https://user-images.githubusercontent.com/88286148/130352343-b137d9aa-e9c4-44fa-a484-e1a2427a1ac9.png)

I've noticed this for a few days now. It takes up space and can be quite the problem when the user sends TLs with a text box emoji.

**Comment by uetchy** [comment]
The fix already landed on the dev branch and will be available soon
https://github.com/HolodexNet/Holodex/pull/381

**Comment by sphinxrave** [comment]
Landed
