### ISSUE TITLE
[Multiview] Feature Request: Quick Media Controls

### ISSUE THREAD

**Issue by ikenaerion** [HolodexNet/Holodex#389]
Whenever watching more than 2 streams at the same time might only want to listen to one stream's audio at the same time. A control or cell widget with which to set the current audio stream with only one click might be a huge experience improvement.
I'm aware of the current Media Controls, but one needs to:

1. Go to the media controls 
2. Un-mute the stream we want to listen to 
3. Mute all other channels

What I propose is a cell (or a side panel) that has each one of the streams as buttons in which clicking one of the buttons results in all streams but the clicked one being muted. This allows for quickly changing audio streams with only one click.
An alternative to this proposal would be implementing a "Solo" button on each stream cell. Clicking this button would mute all other streams. Although, I see that the frame is hidden when the stream is playing.

**Comment by RiceCakess** [comment]
Added Mute Others (mutes all streams except one) in #394, pending release
