### ISSUE TITLE
Feature Request: Better vertical viewing

### ISSUE THREAD

**Issue by xGigaa** [HolodexNet/Holodex#391]
Viewing streams on a vertical monitor puts the chat on the right side next to the video.
This makes sense if you are viewing the stream on a horizontal monitor but not on a vertical one.
Ideally it should look like how Youtube is doing it:
![image](https://user-images.githubusercontent.com/24317395/131278533-5a8d0438-af22-464b-a375-ca07f95ac6ef.png)

**Comment by RiceCakess** [comment]
Fixed in Holodex 2.25
