### ISSUE TITLE
TLdex box appears with clips

### ISSUE THREAD

**Issue by sameyepatch** [HolodexNet/Holodex#401]
To be honest I don't really remember if this was the usual behavior but since last update I've been noticing that the TLdex box appears even when watching clips (which are supposed to be already translated and don't have chat history)

![image](https://user-images.githubusercontent.com/31149431/132113937-b2560dc9-184b-4e3f-ae28-d1e8670cd692.png)

Version: 2.18.1

**Comment by RiceCakess** [comment]
This is a bug from latest update, thanks for report! Will get a fix out soon
