### ISSUE TITLE
 Problem login with Google

### ISSUE THREAD

**Issue by Weisswelt** [HolodexNet/Holodex#406]
When I click on the button "Login with Google", a pop-up will not appear

I'm using Chrome and I don't have this problem with Twitter or Discord

Is there any solution for this problem?

![Holodex](https://user-images.githubusercontent.com/90492818/132936301-026d951a-9383-4cdb-8ee9-bdd1e219a1de.png)

**Comment by sphinxrave** [comment]
click it twice, it works. First click is weird though, i'll go investigate that but it's not a huge problem.
