### ISSUE TITLE
Feature Request: Music - Hide/Minimize button

### ISSUE THREAD

**Issue by sealnaga** [HolodexNet/Holodex#412]
It'd be nice if the music bar have a button to hide/minimize it because sometimes I'd like to have music or bgm while watching a livestream using the Multiview feature.

![image](https://user-images.githubusercontent.com/74229992/133285332-698a5af0-3f07-4996-bcda-9bc330224541.png)
at the moment my screen would look like this if I'm using the music feature while in Multiview, I'd like to be able to minimize it like how you can minimize the toolbar in Multiview. 

I can just close it but then I wouldn't be able to listen to my playlist while watching streams or clips

**Comment by sphinxrave** [comment]
Closed by #423
