### ISSUE TITLE
Urls in TLdex are truncated and non-clickable

### ISSUE THREAD

**Issue by theultramage** [HolodexNet/Holodex#420]
When a message recorded by TLdex contains an url, the url gets truncated (and possibly the rest of the message as well). On youtube it shows truncated as well, but there it also gets linkified and is clickable - although it has to go through youtube's link filter, so the url is obscured on-hover.

As a sample of this behavior, check https://holodex.net/watch/jnEfOYS9aDo TLdex at -0:11.

I have checked chat-downloader's json and there the message appears in full text form. So the data is available, but perhaps TLdex is obtaining it from another field in the data, or a from different data source altogether.

**Comment by theultramage** [comment]
It turned out that the raw youtube data contains an arrray of 'runs' that together form the full chat message, where the url text is indeed truncated, and the link points to youtube's link redirect. It also turned out that chat-downloader does extensive processing on this data (which includes parsing out the original url from the redirect link) to make it easier to consume.

**Comment by sphinxrave** [comment]
fixed.

can't fix old ones though, so they stay broken.
