### ISSUE TITLE
Feature request: Recommend clips from the same source in "Clips"

### ISSUE THREAD

**Issue by sameyepatch** [HolodexNet/Holodex#422]
When watching a clip, the source stream appears to the right of the video (in most cases) and below it, other recommended videos. 
When watching an archive, below it appear clips related to that particular stream.
Most of the time when I want to watch clips of a stream, I go to the source, click on a related clip, then go back to the stream after watching the clip to watch another.

I think it would be easier to have a list of "From the same source" clips between the "Source" and "Recommended" sections when watching a clip so we could be able to watch several clips from a stream right after another without having to visit the archive again.

**Comment by sphinxrave** [comment]
Not too difficult, but in some occasions, clips tag a common video as a source, which causes a ton of headaches coz that video might have 300 clips, as a result. Suppressing that part is kinda annoying.

**Comment by RiceCakess** [comment]
Added in 2.25 #481
