### ISSUE TITLE
API commentSearch and videoSearch ignores limit when paginated is set

### ISSUE THREAD

**Issue by getBoolean** [HolodexNet/Holodex#441]
The API returns all matching items instead of limiting the number of items returned based on the limit set

To Reproduce:
1. Go to https://holodex.stoplight.io/docs/holodex/b3A6MTE2NDUyNTI-create-a-search-video-search
2. Enter this in post request box:
```json
{
  "sort": "newest",
  "target": [
    "stream",
    "clip"
  ],
  "topic": [
    "singing"
  ],
  "comment": "Lemon",
  "paginated": false,
  "offset": 0,
  "limit": 5
}
```
3. See that it returns more than 5 items. If paginated is true, it works as intended

**Comment by sphinxrave** [comment]
fixed in staging, awaiting deploy

**Comment by sphinxrave** [comment]
deployed.
