### ISSUE TITLE
Add translations to videos that don't have live translation chat

### ISSUE THREAD

**Issue by VicnAbi** [HolodexNet/Holodex#451]
Nabi created an official channel to upload her Twitch VOD. 
https://www.youtube.com/channel/UClwpAJOWq7TxZX_H_vOI4Fw
The log file of the translation on Twitch is perfectly compatible with the video. So it is possible to replay through Holodex's interface with translation.
But I don't think this requirement will be accepted because it's not easy to automate and it's a function for only one vtuber.
I will fork Holodex and implement the requirements.
If there is no problem applying it differently than I thought, or if you know another similar vtubers, please write a comment.

**Comment by RiceCakess** [comment]
Endpoint is ready, (no bulk endpoint yet, only individual) 
`POST https://holodex.net/api/v2/videos/<video_id>/chats?lang=<lang code>`
Header: `X-APIKEY: <your api key>  `

body: 
```
{ 
    name: string // author name
    timestamp: string | number // Unix timestamp in milliseconds
    message: string // Translation message
}
```

**Comment by VicnAbi** [comment]
I checked the api success. Thank you!
