### ISSUE TITLE
Cells still getting pushed down on multiview (Microsoft Edge)

### ISSUE THREAD

**Issue by LeeroyGarfield** [HolodexNet/Holodex#457]
I read in the changelog that the cell being pushed down in certain cases is fixed, however it's still happening in the latest version of Microsoft Edge in my case.

**Comment by LeeroyGarfield** [comment]
Strangely, when I change my multiview to any preset and edit it from there, it works normally. However, when I clear the multiview and then add a new cell, the bug appears when you try to drag to adjust the cell.

**Comment by LeeroyGarfield** [comment]
Okay, the devs seems to mentioned this issue as well, I can confirm that any preset with more than one cell is normal. A single cell, is causing this bug.

**Comment by LeeroyGarfield** [comment]
I just found out that it's a full-scale bug that can be caused by any preset. When you drag the bottom and bottom-corners adjustment handles, the bug breaks everything when one cell is closest to the bottom of the screen.

**Comment by RiceCakess** [comment]
I’m not near my computer, but I deployed the hot fix for this issue. Should be getting an update soon
