### ISSUE TITLE
Wrong list of channels displayed when "Favourites" was selected in Multiview

### ISSUE THREAD

**Issue by yk6** [HolodexNet/Holodex#460]
Version: 2.22.1

Tried selecting other list like Nijisanji, which displays correctly. Then it does not display as expected again when switching back to Favorites

![image](https://user-images.githubusercontent.com/16903527/140542023-20809d66-1a33-4ec6-b910-072203a0df18.png)
![image](https://user-images.githubusercontent.com/16903527/140542049-391e9073-9fd5-456c-9020-c2dba6104175.png)

**Comment by sphinxrave** [comment]
Quon Tama is not streaming (probably), however, Flare, Shion and Nene are having streams with Hoshimachi Suisei in them.
