### ISSUE TITLE
Feature Request: Play videos using Invidious

### ISSUE THREAD

**Issue by uShldGetCeleste** [HolodexNet/Holodex#498]
Could be cool if invidious was built into the site and could be enabled or if you could proxy videos through an already existing invidious instance

Invidious: https://github.com/iv-org/invidious
Invidious instances: https://docs.invidious.io/Invidious-Instances.md

**Comment by sphinxrave** [comment]
Absolutely not. It does not contribute back views nor support channels through monetization. While I'm of the opinion that superchat > premium > ads in revenue power, Holodex shouldn't actively take a creator-hostile stance at any point.

![image](https://user-images.githubusercontent.com/62570796/147862741-f491a9b9-dd4f-4db9-bcc1-07612d0a1df8.png)
