### ISSUE TITLE
"This Live Event is no longer available" on every stream in multiview

### ISSUE THREAD

**Issue by ShimmerFairy** [HolodexNet/Holodex#505]
While using firefox, no youtube videos work in multiview anymore. Youtube itself works fine, of course. I've tried turning off every extension that could conceivably cause the issue, as well as changing the user agent, and nothing works. The only way I can see it working is by using a chromium-based browser.

**Comment by sphinxrave** [comment]
https://twitter.com/holodex/status/1481688996627435520
