### ISSUE TITLE
Feature Request: Calendar View

### ISSUE THREAD

**Issue by pockydonut** [HolodexNet/Holodex#520]
A calendar-style view can be useful for seeing upcoming stream times at a glance. For example, the "Stream Calendar by KFP Crew" project (https://www.holocal.moe/calendar.html) supports this:

![image](https://user-images.githubusercontent.com/98051531/150716270-247de13f-d90e-4786-9d2b-0aa59a58a5dd.png)

I'd be happy to implement this feature and wanted to gather any ideas or suggestions before diving in.

(An interesting related feature could be to expose iCal feeds to add to a calendar app. I think there's still value in also having a built-in calendar UI.)

**Comment by RiceCakess** [comment]
That would be awesome, we have this on the idea list, but no time to implement. I don't really have a good idea of what it should look like, but maybe start [here?](https://vuetifyjs.com/en/components/calendars) 

We can iterate on the design/functionality

**Comment by RiceCakess** [comment]
Forgot to add that one of our devs did setup an iCal endpoint, so that's ready to go. We just haven't exposed it to the public, but this feature will be a good place to make it visible

**Comment by EffortlessFury** [comment]
Is there anything the release is pending on?

**Comment by uetchy** [comment]
I have already planted all the necessary API endpoints last year but kind of forgot to expose them on the UI.
Anyways I'm currently working on UI and it will be available for everyone soon™️

![CleanShot 2022-07-15 at 21 04 37@2x](https://user-images.githubusercontent.com/431808/179219794-2ab458e3-93e9-4a5a-a235-d8cd52bc889e.png)

**Comment by sphinxrave** [comment]
This is now released on production.
