### ISSUE TITLE
Multiview countdowns disagree

### ISSUE THREAD

**Issue by SubstandardZeal** [HolodexNet/Holodex#542]
In the multiview pane, the icon countdown overlay disagrees with the hover/popdown countdown.

It appears to be a difference in rounding behavior.

See here the rightmost icon says "one hour" while the hover countdown says "two hours":
![image](https://user-images.githubusercontent.com/21998611/155229193-e003fec6-eda6-46c5-a03d-b5bf6748f84f.png)

---
Firefox: 98.0b7

**Comment by RiceCakess** [comment]
Fixed
