### ISSUE TITLE
Feature request: Dark mode for live chat replay (from archived videos)

### ISSUE THREAD

**Issue by Shinayaya** [HolodexNet/Holodex#545]
For some reason, live chat replay for archived videos has white background, which kind of sucks, especially when streams which are currently live do have a dark background for their chat.

It would be nice if a dark mode option could be addded.

**Comment by RiceCakess** [comment]
This is fixed in upcoming release of the extension. Pending chrome store approval

https://github.com/HolodexNet/Holodex-Plus/blob/dev/CHANGELOG.md
