### ISSUE TITLE
TLdex spoiler free

### ISSUE THREAD

**Issue by DarlockX** [HolodexNet/Holodex#547]
a way to hide all future messages so they don't spoil anything or at least don't auto scroll beyond current message

**Comment by MonMonMnemonics** [comment]
@RiceCakess , @sphinxrave, I'm planning to make this an option that is NOT turned on by default, will that work?

**Comment by sphinxrave** [comment]
OK

**Comment by MonMonMnemonics** [comment]
should have made a separate branch and pull request for this, sorry,
But it's done in https://github.com/HolodexNet/Holodex/commit/8e17421fe2d2721f36e80ba1e388db5bfa4ce3d0
