### ISSUE TITLE
YouTube's j/k/l shortcuts activate while searching in the music tab

### ISSUE THREAD

**Issue by SubstandardZeal** [HolodexNet/Holodex#549]
I expected that when in the music tab/pane/thing the `j/k/l` YouTube playback shortcuts would only activate while the mini player was selected or perhaps the control bar at the bottom.

Instead they activate and seek the song that is playing forward/back even when the music search bar is selected and a user is searching.

![image](https://user-images.githubusercontent.com/21998611/159405868-cae2343d-3381-427c-a797-f938f2b810fa.png)

---
I have tested this on:
Firefox: `99.0b5` & `99.0b6` (also with a fresh profile)
Edge: `Version 99.0.1150.46 (Official build) (64-bit)`

**Comment by sphinxrave** [comment]
Thanks for the bug report, but we'll be deleting that whole feature in a couple days so ....

**Comment by RiceCakess** [comment]
To give more context, we are launching music as a new website separate from Holodex. It's being moved to a different place.
