### ISSUE TITLE
CSP Issue preventing stream thumbnails from being downloaded on the Favorites subpage

### ISSUE THREAD

**Issue by AterialDawn** [HolodexNet/Holodex#556]
Due to what appears to be a CSP issue, thumbnails on the favorites page aren't downloading. They correctly download if you load the Home page first, and then swap over to favorites, but if you refresh the favorites page (forcing your browser to download the Favorites.html page with the CSP settings) most thumbnails will no longer load

Here's a screenshot of me refreshing the homepage and showing that there is no CSP response header on this
![1](https://user-images.githubusercontent.com/15097070/161013496-a907deb2-3dbe-45c8-ab33-2a695a33d146.png)

Here's one showing how the favorites page SHOULD look like
![2](https://user-images.githubusercontent.com/15097070/161013604-31c61a7e-eb79-4b47-adc4-cac9c04ebe1a.png)

And here's how the page looks if you load the favorites page directly.
![3](https://user-images.githubusercontent.com/15097070/161014651-f47d60a0-5a95-4635-b877-f7d7531fd90d.png)

All thumbnails that fail to load are shown in the network tab with CSP as the reason for them not loading. The console also shows a ton of these messages
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://i.ytimg.com/vi/Yv2_XjybbXc/mqdefault.jpg (“img-src”). [vendor.775ecdeb.js:76:212](https://holodex.net/assets/vendor.775ecdeb.js)
Content Security Policy: The page’s settings blocked the loading of a resource at https://i.ytimg.com/vi/bQAqoDIEV_o/mqdefault.jpg (“img-src”). [vendor.775ecdeb.js:76:212](https://holodex.net/assets/vendor.775ecdeb.js)
Content Security Policy: The page’s settings blocked the loading of a resource at https://i.ytimg.com/vi/eaNR-Ti-bNo/mqdefault.jpg (“img-src”).
```

**Comment by RiceCakess** [comment]
@sphinxrave has resolve this issue. 

Please hard refresh with (ctrl + shift + r), and let us know if this problem persists. Thanks!
