### ISSUE TITLE
The link in holodex singing video to musicdex is an error

### ISSUE THREAD

**Issue by ShouChunWu** [HolodexNet/Holodex#558]
The link in holodex singing video to musicdex lacks a slash.

![image](https://user-images.githubusercontent.com/43112887/162079206-6dc314f6-f712-4d28-89f3-ffac4d0b5082.png)

error
<img width="274" alt="image" src="https://user-images.githubusercontent.com/43112887/162079507-2471d875-414c-4317-9429-4a530a176262.png">

correct
<img width="283" alt="image" src="https://user-images.githubusercontent.com/43112887/162079693-6c879f03-bc65-4395-a852-e11a348cad4f.png">

**Comment by uetchy** [comment]
Nice catch👍 Fixed
