### ISSUE TITLE
Multiview cells reload when deleting an older cell

### ISSUE THREAD

**Issue by SubstandardZeal** [HolodexNet/Holodex#584]
### Steps

1. Open and play multiple video cells
2. clear/delete the first cell

![image](https://user-images.githubusercontent.com/21998611/168947002-1d11563c-e6ad-46f3-9ca6-3286584dfb58.png)

### Expected Behavior

The remaining cells rearrange but continue playing.

### Actual Behavior

All cells opened after the deleted cell are reloaded

---
Note that this only seems to happen in certain arrangements. For example, when the window is very small it seems to behave as expected, perhaps because of the mobile auto layouts?

Firefox: 101.0b7 
Edge: 101.0.1210.47
Windows 10 Pro: 21H2

**Comment by michaelnguyenm** [comment]
You can read more in #504 but probably won't be fixed unless Holodex gets rewritten

**Comment by SubstandardZeal** [comment]
Ah, my bad. I searched for other issues but somehow didn't see that one. Should I close this then?

**Comment by sphinxrave** [comment]
Will be fixed as part of Holodex 3.0

**Comment by sphinxrave** [comment]
Fixed thanks to Oliver's efforts in the above PRs <3
