### ISSUE TITLE
Vtuber addtional request: MUS1CA

### ISSUE THREAD

**Issue by fxavierho123** [HolodexNet/Holodex#589]
Can you guys add a awesome Vsinger Mus1ca? She is one of the very best singer that I have ever heard. She sang over 200 covers already, I will be very appreciated if you guys can include her into the website.
Channel URL: https://www.youtube.com/c/Vsingermusicachannel
English name: MUS1CA
Twitter ID: @MUS1CA_vsinge

**Comment by RiceCakess** [comment]
Channel request form is here: https://holodex.net/addChannel
