### ISSUE TITLE
View automatically finished when the live did not

### ISSUE THREAD

**Issue by arubar0** [HolodexNet/Holodex#591]
Hello there... idk if this actually was addressed but I couldn't find it, at least, in oppened issues.

The thing is that at some poit, I get to this page, sometimes just once, sometimes repeatedly at the point of the live almost being imposible to watch... when the live is not even finished.

![image](https://user-images.githubusercontent.com/11367281/173201268-fec4ef16-9488-400e-80b9-862e8b6d8d1e.png)

It has been happening to me since I discovered this tool (like two years ago).

**Comment by sphinxrave** [comment]
unfortunately that's just Youtube itself screwing up, when the streamer's internet quality is bad the Embed Player (which we use) have more bugs than the Youtube.com Player. 

I obviously can't fix youtube bugs, so we're stuck.

Maybe try installing Holodex+ extension (can find instruction on the about page) and it might help the error, but I forgot if there's error mitigating features in that extension...
