### ISSUE TITLE
Feature request: Add view count for clips and archive

### ISSUE THREAD

**Issue by koteq** [HolodexNet/Holodex#597]
![image](https://user-images.githubusercontent.com/1192090/181835715-4721f4ff-5a43-4b84-8078-48e039e906cd.png)

Can Holodex have the same convenient view count info as on YouTube?

I'm not aware of the underlying Holodex nor HoloAPI implementation, so I can't guess how hard it can be adding that, but It'd be cool to have that eventually.

I have [a user script](https://gist.github.com/koteq/f132679266d2132a0cc7ec7ea6462457) that augments Holodex as I'd like. This script relies on YouTube Data API v3 and requires API token to run.

**Comment by sphinxrave** [comment]
Our videos update too infrequently for accurate view count, although it is possible (and even quite accurate after the video 'cools down'). We also just aren't very much about those kinds of numbers. 

Cool userscript though.
