### ISSUE TITLE
Feature Request: navigation based on History API

### ISSUE THREAD

**Issue by LiviaMedeiros** [HolodexNet/Holodex#607]
Navigating on homepage is a bit confusing, especially on mobile devices. Switching between [`live/upcoming`](https://holodex.net/), [`archive`](https://holodex.net/#archive) and [`clips`](https://holodex.net/#clips) works via urlhashes on the same page, while other destinations are handled by separate pathnames.

For example, if user selects `archive` and then `clips` and then clicks native "go back" button, they will be moved on previous history entity (which might be not at holodex) instead of returning to `archive`, because urlhash-based transitions are not pushed to history stack.

This can be solved by `History.pushState()` method and `popstate` event of [`History API`](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

**Comment by sphinxrave** [comment]
Not super high priority for Holodex 2 but we can certainly have this feature built into v3.

**Comment by LogicalContradiction** [comment]
I'm interested in working on this issue. Is there anyone else currently working on it?
