### ISSUE TITLE
Multiview: A finished stream will restart on its own

### ISSUE THREAD

**Issue by cmalfet** [HolodexNet/Holodex#610]
When I'm watching, I'll have at most four streams/VODs with their chats open on Multiview. When a stream finishes, I'll usually just leave the cell alone until I want to replace it with a new one so I don't have to deal with shuffling the cells back around. Ever since the most recent Holodex update, the streams will automatically restart from the beginning eventually. This never happened before so is this a bug?

I'm using Chrome, with my Multiview in a separate window on a second monitor. I have the Holodex+ extension installed.

**Comment by sphinxrave** [comment]
Closed by #612
