### ISSUE TITLE
[API] JSON API replies have a mix value set of empty and null

### ISSUE THREAD

**Issue by cyberofficial** [HolodexNet/Holodex#643]
When retrieving data via api the replies can return back null or empty keys

Example of null
![s1kM82Wonk](https://user-images.githubusercontent.com/19499442/202243141-9320e910-d35f-4859-b09e-89a7c55265ce.png)

Example of Empty
![opera_ZiCJ0WdLwW](https://user-images.githubusercontent.com/19499442/202243793-8f9c3e57-2df4-44d6-a122-fa4d9ae2eeee.png)

This results in having final replies having " " as returns rather having data discarded for clients.
![opera_MCi6ZOhsn9](https://user-images.githubusercontent.com/19499442/202245162-44292074-90c4-4964-85dc-5af132f7ebbd.png)

Yes we clients could write some code to remove the empty sets, but this should be prevented at home base level rather client side level. Could even save a few bytes by making the empty into null server side. If a value is empty, it's better to serve a null value rather empty value.

API call where this happens, (could be other places too): https://holodex.net/api/v2/channels?limit=100&offset=0&type=vtuber&org=Hololive&sort=suborg

**Comment by sphinxrave** [comment]
Fixed the erroneous channels. Will put in some code on serverside to prevent empty values on that field! :+1:
