### ISSUE TITLE
multiview archive sync not working at higher playback speed

### ISSUE THREAD

**Issue by nadomodan** [HolodexNet/Holodex#651]
![image](https://user-images.githubusercontent.com/10760147/206335146-81406753-0701-4b6d-ad70-bd621dd40ed9.png)

when using the archive sync feature to play 2 stream archives simultaneously each set to playback speed 2x the videos will keep stuttering and re-syncing despite playing at the same speed

**Comment by sphinxrave** [comment]
Limitation of the technology, I'm afraid.

**Comment by meiamsome** [comment]
I think we should re-open this, as it is possible to control the playback rate of the YouTube streams via the API, and for Twitch streams we could just warn the user to change the speed on the player, or disable the option based on the videos selected.

I already have a working MVP on my local, so happy to pick this up and carry it to completion.
