### ISSUE TITLE
Discussion: HolodexVR?

### ISSUE THREAD

**Issue by DaniruKun** [HolodexNet/Holodex#652]
More like Holodex-XR ww

Holodex literally has Holo in the name, and is oriented around having one or multiple stream windows.
On AR/VR headsets, you have a ton of free space for windows, so having a native Holodex experience fits this usecase really well.
You can open the existing Holodex website already in XR headset browsers, however it is a very awkward experience since you are trying to hit very small UI elements with shaky hands (nevermind hand tracking input).

Of course, it would be great to have this be cross-platform, so I propose it is implemented as a WebXR app: https://immersiveweb.dev 

This also allows to reuse a bunch of existing Holodex client code. In addition, it's now possible to integrate some nice HMD-specific features (for example, [Quest Web Launch](https://developer.oculus.com/documentation/web/web-launch/)).

The stack will probably be something like 
- [three.js](https://threejs.org)
- [A-frame](https://aframe.io)

Of course, the APIs feature a ton of cool stuff like hand tracking and spatial anchors. I would definitely be up for researching this and making a basic prototype!

The only main blocker might be Youtube playback - most YT wrapper implementations rely on their `iframe`.
In that case it might make more sense to just develop a standalone app that doesn't have the WebGL limitations.

**Comment by sphinxrave** [comment]
Sounds like a fancy idea, but i don't think dev team has bandwidth, feel free to explore it though 👍 i'm sure you can find some novel XR interaction experiences from this, but I haven't put much thought into how scheduling data delivery and complex video searching can be coupled together with XR/VR experiences.

Well you're probably in our discord already but feel free to chime in on anything
