### ISSUE TITLE
Newly made playlists not saving properly

### ISSUE THREAD

**Issue by Capy282** [HolodexNet/Holodex#667]
For the past couple weeks I haven't been able to save any new playlists that I've created. Anytime I hit the save button it just creates a blank playlist with no videos and the same title without saving the current playlist. Once I abandon the playlist I have all the videos in and then go into the blank playlist that was saved, that will begin to work as intended where I can save videos normally. Old playlists that we're made before this bug began seem to work fine still, it's only new playlists. This happens to me both on desktop and mobile. I am using the most current version of Firefox. I've tried logging in/out, clearing cache/cookies but nothing works so it would be greatly appreciated if you could fix this as soon as you can, thank you!

**Comment by NeloBlivion** [comment]
Tried fixing on https://staging.holodex.net, can you test if it works properly now?

**Comment by Capy282** [comment]
Okay yea it works on the beta site. It saves the playlist and doesn't make any blank copies. Also one other thing I forgot to mention, whenever I delete a playlist it doesn't automatically update in the playlist section. It turns the playlist that I deleted into an empty base playlist while the old playlist will remain visible, but can't be clicked on, The only way I've seen to fix that is to refresh the page for it to disappear. Thank you for fixing the main issue so quickly though!

**Comment by sphinxrave** [comment]
The server change has been deployed to the production API.

Thanks for the report Capy and quick fix Nelo <3
