### ISSUE TITLE
Search functionality broken

### ISSUE THREAD

**Issue by Safebox36** [HolodexNet/Holodex#668]
I noticed a few days ago that the search functionality has stopped working.
Before it was just slow for clips compared to comments but now the results just don't show up at all.

I left it cause I thought maybe it had been noticed or was just a caching issue on my browser.
But even in incognito, on another browser, and on my mobile it's still not working.

**Comment by sphinxrave** [comment]
Figured it out. Fixed now on staging and production. Please verify and thanks for the report!👍

**Comment by Atario** [comment]
This has happened again  :(

**Comment by Linden10** [comment]
> This has happened again :(

Same same, for the past month or so the search functionality has been not working at all!
It started when searching was slow back in March...then it stopped working altogether...

Hope this can be fixed again!
