### ISSUE TITLE
vuetify migration checklist

### ISSUE THREAD

**Issue by RiceCakess** [HolodexNet/Holodex#672]
components that need to be migrated. Check off when component exist **and** all instances are replaced 

- [x] <v-col
- [x] <v-autocomplete
- [x] <v-lazy
- [x] <v-menu
- [x] <v-avatar
- [x] <v-img
- [x] <v-fade
- [x] <v-overlay
- [x] <v-btn
- [x] <v-icon
- [x] <v-sheet
- [x] <v-card (and a bunch of card related stuff like card-text and card-title)
- [x] <v-progress
- [x] <v-dialog
- [x] <v-text
- [x] <v-divider
- [x] <v-spacer
- [x] <v-hover
- [x] <v-tooltip
- [x] <v-slide
- [x] <v-list
- [x] <v-window
- [x] <v-snackbar
- [x] <v-row
- [x] <v-select
- [x] <v-container
- [x] <v-alert
- [x] <v-color
- [x] <v-expand-transition
- [x] <v-checkbox
- [x] <v-system-bar
- [x] <v-simple
- [x] <v-textarea
- [x] <v-tabs
- [x] <v-tab
- [x] <v-form

**Comment by sphinxrave** [comment]
Last boss:

- [ ] v-app
- [ ] v-app-bar
- [ ] v-footer
- [ ] v-navigation-drawer
