### ISSUE TITLE
Membership streams not picking up TLs

### ISSUE THREAD

**Issue by cmalfet** [HolodexNet/Holodex#698]
There seems to be an issue that appeared in the last month or so where TLdex isn't picking up live TLs in membership streams.

**Comment by NeloBlivion** [comment]
If it's happening in chat, it can't because the chat is private to members. The TLer has to be using the TL client on-site.

**Comment by cmalfet** [comment]
That's the strange part, it was capturing until just recently. In one instance, I believe the TLer normally uses the client and sends to both TLdex and live chat.

**Comment by sphinxrave** [comment]
Only happens when TLDex is used to translate mengen. Otherwise we don't pickup chat, i think.
