### ISSUE TITLE
iCal feeds stopped working

### ISSUE THREAD

**Issue by pltnmvenus** [HolodexNet/Holodex#721]
Starting around sometime last night, none of the iCal feeds seem to work anymore. (Was a little after 8AM UTC, judging by the log files; I have a script that fetches the iCal and pushes it to a Google Calendar to get around Google's ridiculously slow iCal sync rate.)

Fetching the URL just returns an HTML page. It appears to happen no matter how the request is performed - curl, wget, Python, Firefox, etc. It also doesn't seem to matter what iCal is requested - search-based, favorite-based, english names or not, etc. I also tried both while logged into Holodex and logged out in a private browsing window.

Up until this morning it returned iCal data as expected. If there's some magic extra information, header, user agent, or whatever that will make it work, I don't see it.

```
$ curl -s 'https://holodex.net/live.ics?org=Hololive&preferEnglishName=1' | head
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="viewport-fit=cover,initial-scale=1.0,width=device-width,user-scalable=no,maximum-scale=1.0" />
    <meta name="theme-color" content="#42a5f5" />

    <!-- SEOCONTENTSTART -->
```

Viewing this page in the browser just has a mostly-blank page with "Content not found / Return home".

**Comment by RiceCakess** [comment]
Hello made a load balancer optimization that caused this to break. It should be fixed now.
