### ISSUE TITLE
Feature Request: Support Kick.com stream URLs in MultiView 'Add Custom URL'

### ISSUE THREAD

**Issue by FlaminSarge** [HolodexNet/Holodex#729]
As above, allow adding Kick.com streams/chat to Multiview.

This would require a decent bit of rework to how Multiview does custom URLs since it currently assumes that if a URL isn't Twitch, it's YouTube (nearly everywhere), but otherwise the handling for Twitch should carry over pretty well to Kick (less confident about the TwitchPlayer component though, as they don't go Twitch's route and instead tell you to use an iframe).

**Comment by FlaminSarge** [comment]
Planning to attempt a PR for this sometime soon, as well, if I can manage it.

**Comment by RiceCakess** [comment]
Hello! We don't have any plans to support Kick at this time. We are only interested in platforms that have a large vtuber presence.

We will appreciate contributions to any of the other existing issues!

**Comment by FlaminSarge** [comment]
> Hello! We don't have any plans to support Kick at this time. We are only interested in platforms that have a large vtuber presence.
> 
> We will appreciate contributions to any of the other existing issues!

How large of a presence? The category on Kick has a decent amount of activity, though of course nowhere near Twitch/YT given the recency of the platform https://kick.com/categories/games/v-tubers

**Comment by sphinxrave** [comment]
To a degree where a number of Vtubers are there with enough following to warrant the work put into supporting the platform. A gander at the site shows around 400 viewers in category with the most popular handling <100. In addition most of the streams are 18+, but we try to keep content of that nature out of platform - mainly by piggybacking off YouTube and twitch whose platform policies will ban violators.

You're still welcome currently to provide stream frame "placeholders" for Vtubers (who are on Holodex already) who are streaming on kick much like the support we have for Twitcast and X-spaces. Ideally these should label the R18 nature without using R18 thumbnails.

However, vtuber addition is still gated by our notability requirements on the Add Channel page and manual approval by the moderation team.

**Comment by FlaminSarge** [comment]
> However, vtuber addition is still gated by our notability requirements on the Add Channel page and manual approval by the moderation team.

Understood; what about custom URLs in Multidex? I understand that there's no reason at the moment to include most of these creators in Holodex's main UI, but Multidex is one of the best ways to watch multiple streams across YT and Twitch I've used, and it would be useful for Kick URLs to also be usable. If I can get a working PR up for specifically that, would there be any outstanding reason not to merge it?

**Comment by FlaminSarge** [comment]
@RiceCakess @sphinxrave any updates on the above re: specifically Multidex support? As it stands, Multidex supports any Twitch or YouTube URL, and it would be great to be able to add any Kick URL to that as well. If I manage to get a working PR for that, would there be any blockers on your end for merging it?
