### ISSUE TITLE
Function to rearrange Favorites list in sidebar

### ISSUE THREAD

**Issue by planetarian** [HolodexNet/Holodex#91]
As-is, only a few items can be displayed in the Favorites list in the sidebar, while the rest get collapsed inside the "Show All" option. 

Alphabetical order is used by default, but that's not necessarily the most ideal criteria to use to determine whether to display an item top-level or behind a click.

It would be nice to have a mechanism for rearranging this list manually, so I could keep my top-most-frequently-watched streamers always visible, and simply have the less-viewed favorites collapsed into the menu.

**Comment by sphinxrave** [comment]
Right now it's just ordered in list order of next streaming, which i think makes more sense than having a simple ordered list. let me know if this is a good idea or not. Closing for now (tidying up issues)
